### PR TITLE
handle internal stylesheets

### LINKED ISSUE #35: Handle inline <style>s
I've been playing around with react-magic, testing it on a number of different websites.  I got one syntax error quite often.  I've included a few examples of this error.

**How to reproduce** For each site I opened up the debug console (in Firefox), and ran this command (taken from the bookmarklet):

        (function(b){function c(){if(0!==d.length){var e=d.shift(),a=b.createElement("script");a.src=e;a.onload=c;b.body.appendChild(a)}}var d=["http://fb.me/react-0.13.3.min.js","http://fb.me/JSXTransformer-0.13.3.js","http://reactjs.github.io/react-magic/magic.min.js"];c();return!1})(document);

| URL | React-Magic Error |
|------------------------------|---------------------------------------------------------------------------------------------------------------|
| http://www.uschs.org/ | Error: Something bad happened when transforming HTML to JSX: Error: Parse Error: Line 268: Unexpected token : |
| http://www.starwars.com/news | Error: Something bad happened when transforming HTML to JSX: Error: Parse Error: Line 5: Unexpected token : |
| http://karl.tech/ | Error: Something bad happened when transforming HTML to JSX: Error: Parse Error: Line 12: Unexpected token : |

Maybe it has to do with inline styles?

### PR DESCRIPTION
**Pull request by sickslives**
Fixes #35

### CODE REVIEW

**Comment by sickslives** [comment]
Actually, style tags in the body are still broken if they contain quotes. Digging deeper!

**Comment by sickslives** [comment]
Not sure what's going on here. The test passes, but [as seen in this fiddle](https://jsfiddle.net/ucgLqtbu/) or when you test this on a real page, the quotes get turned into entities.

**Comment by ssorallen** [comment]
Could you use `dangerouslySetInnerHTML={{__html: JSON.stringify(text)}}` instead of writing to its innerText? Here's a fiddle with the change: https://jsfiddle.net/ucgLqtbu/1/

This opens a security hole though if you ever let user-created content be written inside a `<style>` tag.

**Comment by sickslives** [comment]
That works, but is [what I had before](https://github.com/sickslives/react-magic/blob/01529014a2d8a03065312080baa7199e36ee21f4/src/htmltojsx.js#L444-L446) considered safe? I would think one of the more common use cases of an internal stylesheet would be for custom end-user styles.

**Comment by Daniel15** [comment]
> This opens a security hole though if you ever let user-created content be written inside a <style> tag.

Do you have an example, or is it just a theoretical hole? :)

**Comment by sickslives** [comment]
> Do you have an example, or is it just a theoretical hole? :)

That's in reference to [react's docs on dangerouslySetInnerHTML](https://facebook.github.io/react/tips/dangerously-set-inner-html.html) but I just did a quick test and `<script>` tags nested inside `<style>` tags don't get run, so I don't think it's a danger here.

**Comment by ssorallen** [comment]
> Do you have an example, or is it just a theoretical hole? :)

It's a theoretical hole that I have not proven to be real yet. Since @sickslives tested `<script>` tags inside `<style>` tags, it at least seems not blatantly bad.

**Comment by Daniel15** [comment]
@ssorallen Pushed to NPM as 0.2.5.

**Pull request merged**
